
INSERT INTO word VALUES
('scrumptious','przepyszny','hard'),
('redoubtable','groźny','hard'),
('insouciance','beztroska','hard'),
('turpitude','podłość','hard'),
('blandishment','pochlebstwo','hard'),
('sanctimonious','świętoszkowaty','hard'),
('inveterate','nałogowy','hard'),
('embezzlement','sprzeniewierzenie','hard'),
('incumbent ','beneficjent','hard'),
('recalcitrant','oporny','hard'),
('longiloquence','długomówność','hard'),
('ubiquitous','wszechobecny','hard'),
('promulgate','ogłosić','hard'),
('alacrity','skwapliwość','hard'),
('circumlocution','omówienie','hard'),
('multifarious','różnorodny','hard'),
('pertinacious','zawzięty','hard'),
('impervious','nieprzenikliwy','hard'),
('aberuncate','wyrwać','hard'),
('loquacious ','gadatliwy','hard'),
('gourmand','smakosz','hard'),
('vicissitude','zmienność','hard'),
('adumbrate','zapowiadać','hard'),
('phenomenon','zjawisko','hard'),
('antediluvian','przedpotopowy','hard'),
('commensurate','współmierny','hard'),
('denigrate','oczerniać','hard'),
('egregious','skandaliczny','hard'),
('fallacious','błędny','hard'),
('gratuitous','darmowy','hard'),
('interlocutor','rozmówca','hard'),
('intransigent','nieprzejednany','hard'),
('mendacious','kłamliwy','hard'),
('negligent','niedbały','hard'),
('obstreperous','krzykliwy','hard'),
('preponderance','przewaga','hard'),
('solicitous','zatroskany','hard'),
('turpitude','podłość','hard'),
('vociferous','wrzaskliwy','hard'),
('noxious','toksyczny','medium'),
('travesty','parodia','medium'),
('affluent','zamożny','medium'),
('beguile','oszukać','medium'),
('duress','przymus','medium'),
('enervate','mdleć','medium'),
('instigate','podżegać','medium'),
('mawkish','ckliwy','medium'),
('exile ','wygnać','medium'),
('remiss','niedbały','medium'),
('rescind','odwołać','medium'),
('torpid','bezwładny','medium'),
('yoke','jarzmo','medium'),
('approach','zbliżać się','medium'),
('beautiful','piękny','medium'),
('birthday','urodziny','medium'),
('abject','nikczemny','medium'),
('bereft ','pozbawiony','medium'),
('payment','zapłata','medium'),
('capital','stolica','medium'),
('branch','gałąź','medium'),
('breakfast','śniadanie','medium'),
('acumen','bystrość','medium'),
('certain','pewny','medium'),
('death','śmierć','medium'),
('direct','kierować','medium'),
('education','wykształcenie','medium'),
('everything','wszystko','medium'),
('famous ','sławny','medium'),
('foreign ','zagraniczny','medium'),
('guide ','przewodnik','medium'),
('jealous','zazdrosny','medium'),
('knife','nóż','medium'),
('member','członek','medium'),
('probably ','prawdopodobnie','medium'),
('jewel','klejnot','medium'),
('impossible ','niemożliwe','medium'),
('quarter','ćwierć','medium'),
('feedback','opinie','medium'),
('narrow','wąski','medium'),
('husband','mąż','medium'),
('bond','obligacja','medium'),
('sentence','wyrok','medium'),
('guarantee','gwarancja','medium'),
('instead ','zamiast','medium'),
('employer','pracodawca','medium'),
('mountain','góra','medium'),
('retailer','detalista','medium'),
('employee','pracownik','medium'),
('interest','odsetki','medium'),
('rich','bogaty','medium'),
('silver','srebro','medium'),
('travel ','podróż','medium'),
('gold ','złoto','medium'),
('expensive','drogi','medium'),
('common','pospolity','medium'),
('unemployed','bezrobotny','medium'),
('waiter','kelner','medium'),
('victim ','ofiara','medium'),
('have','mieć','easy'),
('do','robić','easy'),
('say','mowić','easy'),
('make','robić','easy'),
('go','iść','easy'),
('know','wiedzieć','easy'),
('take','brać','easy'),
('see','widzieć','easy'),
('come','przyjść','easy'),
('think','myśleć','easy'),
('want','chcieć','easy'),
('give','dać','easy'),
('use','użyć','easy'),
('find','znaleźć','easy'),
('ask','pytać','easy'),
('work','praca','easy'),
('feel','czuć','easy'),
('person','osoba','easy'),
('man','mężczyzna','easy'),
('woman','kobieta','easy'),
('child','dziecko','easy'),
('time','czas','easy'),
('year','rok','easy'),
('week','tydziń','easy'),
('day','dzień','easy'),
('way','droga','easy'),
('thing','rzecz','easy'),
('world','świat','easy'),
('life','życie','easy'),
('hand','ręka','easy'),
('part','część','easy'),
('eye','oko','easy'),
('place','miejsce','easy'),
('work','praca','easy'),
('point','punkt','easy'),
('number','numer','easy'),
('group','grupa','easy'),
('good','dobry','easy'),
('new','nowy','easy'),
('first','pierwszy','easy'),
('last','ostatni','easy'),
('long','długi','easy'),
('great','wspaniały','easy'),
('little','mały','easy'),
('own','posiadać','easy'),
('old','stary','easy'),
('right','prawo','easy'),
('big','duży','easy'),
('high','wysoko','easy'),
('small','mały','easy'),
('next','następny','easy'),
('early','wcześnie','easy'),
('young','młody','easy'),
('important','ważny','easy');